version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./private.pem:/usr/src/app/private.pem
      # Optional: Add this line if you want "Hot Reload" during development
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
    restart: always